# PyTorch

- Documentação: https://pytorch.org/tutorials/
- Documentação / tensores: https://pytorch.org/docs/stable/tensors.html

# Converter listas em tensores

In [ ]:
import torch
import numpy as np

lista = [[1, 2, 3],
         [3, 4, 5]]

# Converter para o formato default (float)
tensor = torch.Tensor(lista)
print(tensor.dtype)
print(tensor)

# Converter explicitamente para o formato float
tensor = torch.FloatTensor(lista)
print(tensor.dtype)
print(tensor)

# Converter para o formato double
tensor = torch.DoubleTensor(lista)
print(tensor.dtype)
print(tensor)

# Converter para o formato long (para usar com inteiros)
tensor = torch.LongTensor(lista)
print(tensor.dtype)
print(tensor)

torch.float32
tensor([[1., 2., 3.],
        [3., 4., 5.]])
torch.float32
tensor([[1., 2., 3.],
        [3., 4., 5.]])
torch.float64
tensor([[1., 2., 3.],
        [3., 4., 5.]], dtype=torch.float64)
torch.int64
tensor([[1, 2, 3],
        [3, 4, 5]])


# Converter Arrays Numpy em Tensores

- Preserva o tipo do array

In [ ]:
arr = np.random.rand(3,4)
tensor = torch.from_numpy(arr)

print(arr)
print(arr.dtype)

print(tensor)
print(tensor.dtype)

# testando com um array inteiro
arr_int = arr.astype(int)
tensor_int = torch.from_numpy(arr_int)
print(tensor_int)
print(tensor_int.dtype)

[[0.44180622 0.62733002 0.03055699 0.81363674]
 [0.85378284 0.50713798 0.6485855  0.23013855]
 [0.61419776 0.52123903 0.65382318 0.928455  ]]
float64
tensor([[0.4418, 0.6273, 0.0306, 0.8136],
        [0.8538, 0.5071, 0.6486, 0.2301],
        [0.6142, 0.5212, 0.6538, 0.9285]], dtype=torch.float64)
torch.float64
tensor([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]])
torch.int64


# Criar Tensores

In [ ]:
# criar tensores com valroes preenchidos
tensor1 = torch.ones(2, 3) # tensor 2 x 3 com 1
tensor0 = torch.zeros(4, 5) # tensor 4 x 5 com zeros
tensor = torch.randn(5) # tensor 1 dimensão
tensorr = torch.randn(3, 3) # tensor com valroes aleatórios a partir de uma distrib normal

print(tensor1)
print(tensor0)
print(tensor)
print(tensorr)

# criar tensores inserindo valores manualmente
tensor_a = torch.tensor(2) # cria tensor com valor 2
tensor_b = torch.tensor(1) # cria tensor com valor 1
print(tensor_a)
print(tensor_b)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])
tensor([-1.1615,  0.4233, -0.5687,  0.0438,  0.4313])
tensor([[ 0.8810,  1.4079,  0.7375],
        [ 0.5621, -0.0921, -2.0646],
        [ 0.5737,  1.0576, -0.9714]])
tensor(2)
tensor(1)


# Converter tensor em array Numpy

In [ ]:
arr = tensorr.data.numpy()
print(arr)
print(type(arr))

[[ 0.10417994 -0.63135374  0.5973632 ]
 [ 0.14658977 -2.1594198  -0.46093678]
 [ 1.3157661  -0.5733688   0.07517192]]
<class 'numpy.ndarray'>


# Indexação

- Alterando elementos
- Acessa partes do tensor como no numpy
- Acessando fatias do tensor

In [ ]:
print(tensorr)
print()

tensorr[0, 2] = -10 # altera tensor na linha 0 coluna 2
print(tensorr)
print()

# indexando um único elemento (também será um tensor)
print(tensorr[0, 0])
print(tensorr[0, 0].size()) # possui zero dimensões
print()

# acessando fatia do tensor
print(tensorr[0:2]) # printa as linahs 0 e 1
print()
print(tensorr[:, 2]) # printa todas as linhas da coluna 2



tensor([[ 0.1042, -0.6314,  0.5974],
        [ 0.1466, -2.1594, -0.4609],
        [ 1.3158, -0.5734,  0.0752]])

tensor([[  0.1042,  -0.6314, -10.0000],
        [  0.1466,  -2.1594,  -0.4609],
        [  1.3158,  -0.5734,   0.0752]])

tensor(0.1042)
torch.Size([])

tensor([[  0.1042,  -0.6314, -10.0000],
        [  0.1466,  -2.1594,  -0.4609]])

tensor([-10.0000,  -0.4609,   0.0752])


# Operações com Tensores

In [ ]:
tensorA = torch.rand(2, 3)
print(tensorA)
print()

tensorB = torch.rand(2, 3)
print(tensorB)
print()

# somar
print(tensorA + tensorB)
print()

# multiplicar (ponto a ponto)
print(tensorA * tensorB)
print()

# dividir
print(tensorA / tensorB)
print()

# produto interno 2D (multiplicação de matrizes "tradicional")
tensor_a = torch.randn(2, 3)
tensor_b = torch.randn(3, 1)
print(torch.mm(tensor_a, tensor_b))


tensor([[0.0709, 0.9174, 0.3100],
        [0.6108, 0.7856, 0.5949]])

tensor([[0.1702, 0.1611, 0.5411],
        [0.1942, 0.4165, 0.8249]])

tensor([[0.2411, 1.0785, 0.8511],
        [0.8050, 1.2022, 1.4198]])

tensor([[0.0121, 0.1478, 0.1678],
        [0.1186, 0.3272, 0.4907]])

tensor([[0.4167, 5.6946, 0.5730],
        [3.1445, 1.8861, 0.7212]])

tensor([[ 0.9727],
        [-0.1111]])


# Algumas funções úteis

- size(): tamanho do tensor
- view():
  - parâmetro -1: achatar
- shape()

In [ ]:
print(tensor1.shape)
print(tensor1.shape[0]) # dimensão
print()

print(tensor1.size())
print(tensor1.size(0))
print()

print(tensor1.view)
print()

# redimensionar o tensor
tensor3d = torch.randn(2, 2, 3)
print(tensor3d)
print()
print(tensor3d.view(12)) # redimensiona
print(tensor3d.view(tensor3d.size(0), -1)) # mantém a primeira dimensão e achata o restante


# GPU Cast

- Incluir GPU no Collab:
  - Editar -> Configurações do Notebook
- É de extrema importância  

In [ ]:
tensor = torch.randn(10)
print(tensor)

# verifica se gpu está disponível
if torch.cuda.is_available():
    device = torch.device('cuda')
else:
    device = torch.device('cpu')

print(device)

# jogar informações na gpu
tensor = tensor.to(device)
print(tensor)

# Concatenar tensores

In [ ]:
tensor_a = torch.randn(3)
tensor_b = torch.randn(3)

tensor_out = torch.cat( (tensor_a, tensor_b), dim=0 )
print(tensor_out)

tensor([-0.2708, -0.4774,  1.5121,  0.2267, -0.9866, -1.5532])


# Outras funções úteis

- torch.squeeze(): remove uns
- torch.unsqueeze(): adiciona uns

In [ ]:
# TODO

# Exemplos

In [ ]:
import torch
tns = torch.randn(9, 12)
print(tns)
print()

tns1 = tns[0:5, 0:4]
print(tns1)
print()

tns2 = tns[5:, 4:]
print(tns2)
print()

resultado = torch.mm(tns1, tns2)
print(resultado.size())

tensor([[-0.5794, -1.9845,  1.4440,  0.4324,  1.1529,  0.7578, -0.0297, -0.2358,
         -0.8869,  1.4689,  0.7692, -1.3842],
        [ 0.9975, -0.1892, -1.4107, -0.1504, -1.6776, -0.4909, -0.2944,  0.3221,
         -1.9986, -1.5093, -1.1030, -0.0552],
        [ 0.3815, -0.0297,  0.9689, -0.0515, -1.7416, -0.6366, -0.0495,  0.5603,
          0.1199, -1.4405,  0.9648, -1.1838],
        [ 1.7911, -0.6993, -0.0877,  0.1132, -0.0217,  1.3930, -0.1467, -1.1970,
         -0.9997, -1.3253,  1.8491, -0.4106],
        [-0.7146, -1.3468, -3.1704, -0.3383,  0.1341,  0.3317,  1.3199, -0.7033,
          0.9823,  0.7010,  1.2923, -1.4104],
        [-1.8315,  2.0357,  0.6725,  0.2561,  1.1053, -0.5597, -1.6123, -1.6292,
          1.1826, -1.6079, -0.3023,  1.7509],
        [-1.8460,  2.7600, -0.1240, -0.1446,  0.3221, -0.2856,  1.0385,  1.8073,
         -0.5819, -0.8286,  0.7924, -2.9741],
        [ 1.6003, -0.8894, -1.1472, -0.4915,  0.4938,  0.3621, -1.3275,  0.9683,
          0.9405,  0.4907,  0.

# Exercício

- Crie um tensor aleatório tns1 com a dimensionalidade 7 x 7 x 3 e um outro tensor aleatório tns2 de 147 x 1. Modificando apenas tns1 some os dois tensores.

In [ ]:
import torch

tns1 = torch.randn(7, 7, 3)
tns2 = torch.randn(147, 1)

tns1_modific = tns1.view(-1, 1) # achata o tensor
print(tns1_modific + tns2)

tensor([[ 1.5364e+00],
        [-5.1028e-01],
        [-2.0414e-01],
        [-1.1832e+00],
        [-3.3361e-01],
        [ 1.5401e+00],
        [ 6.9926e-01],
        [ 1.7585e+00],
        [-3.7227e-01],
        [ 7.1518e-01],
        [-2.2767e+00],
        [-1.5985e+00],
        [ 1.8639e+00],
        [ 1.4368e+00],
        [ 3.1746e-01],
        [-2.1696e+00],
        [-2.6024e+00],
        [ 1.2230e+00],
        [ 5.1760e-01],
        [-7.8719e-01],
        [-5.2491e-01],
        [ 5.9826e-01],
        [-1.6467e+00],
        [-1.1391e+00],
        [ 1.0160e-01],
        [ 1.4048e+00],
        [ 1.6760e-01],
        [ 4.9121e-02],
        [-1.4742e+00],
        [-5.7720e-01],
        [ 9.3452e-02],
        [ 4.9751e-01],
        [ 3.1624e-01],
        [-2.7237e+00],
        [-1.4413e+00],
        [ 7.0347e-01],
        [-3.4869e-01],
        [-1.0435e+00],
        [ 5.8695e-01],
        [ 5.4010e-01],
        [-2.1607e+00],
        [-1.3675e+00],
        [ 2.9907e+00],
        [ 6