- Documentação: https://pytorch.org/tutorials/
- Documentação / tensores: https://pytorch.org/docs/stable/tensors.html

# Tipos

In [ ]:
# FloatTensor: 32-bit float - é o default

# DoubleTensor: 64-bit float

# HalfTensor: 16-bit float

# IntTensor: 32-bit int

# LongTensor: 64-bit int

# Criar

In [ ]:
import torch

# 0D inserindo valores manualmente
tns_m0 = torch.tensor(5)
print(tns_m0)
print()

# 1D com valores aleat a partir de distrib normal
tns_rn_1d = torch.randn(8)
print(tns_rn_1d)
print()

# 2D com zeros
tns_z = torch.zeros(2, 3)
print(tns_z)
print()

# 2D com uns
tns_o = torch.ones(2, 3)
print(tns_o)
print()

# 2D com valores aleat a partir de distrib normal
tns_rn = torch.randn(2, 3)
print(tns_rn)
print()

# 2D com valores aleat
tns_r = torch.rand(2, 3)
print(tns_r)
print()

tensor(5)

tensor([-0.3017,  0.8973,  3.1591, -0.2370,  0.7509,  1.4763, -1.7741, -0.4327])

tensor([[0., 0., 0.],
        [0., 0., 0.]])

tensor([[1., 1., 1.],
        [1., 1., 1.]])

tensor([[ 0.6456,  0.0618,  0.6351],
        [-0.8390, -0.1186,  0.0262]])

tensor([[0.8893, 0.7211, 0.7808],
        [0.9549, 0.4789, 0.5798]])



# Concatenar

In [ ]:
import torch

tns_a = torch.randn(2)
tns_b = torch.randn(3)

tns_concat = torch.cat((tns_a, tns_b), dim=0)
print(tns_concat)

tensor([ 2.3183, -1.3571, -1.7123,  0.0764,  0.1842])


# Converter

## Lista em Tensor

In [ ]:
import torch

lista = [[1, 2, 3],
         [3, 4, 5]]

# para formato default (float)
tns_f = torch.Tensor(lista)
print(tns_f.dtype)
print(tns_f)
print()

# explicitamente para float
tns_f = torch.FloatTensor(lista)
print(tns_f.dtype)
print(tns_f)
print()

# explicitamente para double
tns_d = torch.DoubleTensor(lista)
print(tns_d.dtype)
print(tns_d)
print()

# explicitamente para long
tns_l = torch.LongTensor(lista)
print(tns_l.dtype)
print(tns_l)
print()

torch.float32
tensor([[1., 2., 3.],
        [3., 4., 5.]])

torch.float32
tensor([[1., 2., 3.],
        [3., 4., 5.]])

torch.float64
tensor([[1., 2., 3.],
        [3., 4., 5.]], dtype=torch.float64)

torch.int64
tensor([[1, 2, 3],
        [3, 4, 5]])



## Array Numpy em Tensor

In [ ]:
import torch
import numpy as np

# cria array float
arr = np.random.rand(3,4)
print(arr)
print(arr.dtype)
print()

# converte par atensor float
tns = torch.from_numpy(arr)
print(tns)
print(tns.dtype)
print()

# cria array int
arr_int = arr.astype(int)
print(arr_int)
print(arr_int.dtype)
print()

# converte para tensor int
tns_int = torch.from_numpy(arr_int)
print(tns_int)
print(tns_int.dtype)
print()

[[0.04898115 0.37520866 0.73462963 0.07324555]
 [0.96913612 0.6699024  0.92780701 0.83796143]
 [0.65606633 0.60508724 0.59466858 0.77717414]]
float64

tensor([[0.0490, 0.3752, 0.7346, 0.0732],
        [0.9691, 0.6699, 0.9278, 0.8380],
        [0.6561, 0.6051, 0.5947, 0.7772]], dtype=torch.float64)
torch.float64

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
int64

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]])
torch.int64



## Tensor em Array Numpy

In [ ]:
import torch

tns = torch.randn(2, 3)

arr = tns.data.numpy()
print(arr)
print(type(arr))

[[1.0024849  0.5722469  0.58960336]
 [0.2986532  0.4889372  0.2892204 ]]
<class 'numpy.ndarray'>


# Indexação

In [ ]:
import torch

# criar
tns = torch.randn(3, 4)
print(tns)
print()

# alterar
tns[0, 1] = 10
print(tns)
print()

# slice
print(tns[0, 0])
print(tns[0:2]) # printa linhas 0 e 1
print(tns[0:2, 0:2]) # até linha 1 e ate col 1
print()

print(tns[1:, 2:]) # linha 1 em diante e coluna 2 em diante
print(tns[:, 1]) # printa todas linhas da coluna 1
print()

tensor([[ 0.7315,  1.7457, -0.5216, -1.2520],
        [ 0.3874, -0.8628,  0.1220, -0.9950],
        [ 1.3138, -0.8152, -1.8716, -1.3057]])

tensor([[ 0.7315, 10.0000, -0.5216, -1.2520],
        [ 0.3874, -0.8628,  0.1220, -0.9950],
        [ 1.3138, -0.8152, -1.8716, -1.3057]])

tensor(0.7315)
tensor([[ 0.7315, 10.0000, -0.5216, -1.2520],
        [ 0.3874, -0.8628,  0.1220, -0.9950]])
tensor([[ 0.7315, 10.0000],
        [ 0.3874, -0.8628]])

tensor([[ 0.1220, -0.9950],
        [-1.8716, -1.3057]])
tensor([10.0000, -0.8628, -0.8152])



# Operações

In [ ]:
import torch

tns_a = torch.ones(2, 3)
tns_b = torch.randn(2, 3)
print(tns_a)
print(tns_b)
print("-" * 40)
print()

# somar
print(tns_a + tns_b)
print()

# subtrair
print(tns_a - tns_b)
print()

# multiplicar ponto a ponto
print(tns_a * tns_b)
print()

# dividir
print(tns_a / tns_b)
print()

In [ ]:
import torchgen

tns_a = torch.randn(2, 3)
tns_b = torch.randn(3, 1)
print(tns_a)
print(tns_b)
print("-" * 40)
print()

# produto interno 2D (multiplicação de matrizes "tradicional")
print(torch.mm(tns_a, tns_b))
print()

# Propriedades

In [ ]:
import torch

tns = torch.randn(3, 4)

# tipo
print(tns.dtype)
print()

# dimensões x e y
print(tns.shape)
print(tns.shape[0]) # dimensão x
print(tns.shape[1]) # dimensão x
print()

torch.float32

torch.Size([3, 4])
3
4



# Métodos

In [ ]:
import torch

tns = torch.randn(2, 2, 3)
print(tns)
print()

# dimensões x, y, z
print(tns.size())
print(tns.size(0))
print(tns.size(1))
print(tns.size(2))
print()

# redimensionar
print(tns.view(12))
print()

# redimensionar mantendo a primeira dimensão e achatando o restante
print(tns.view(tns.size(0), -1))
print()

# GPU Cast

- Incluir GPU no Collab:
    - Editar -> Configurações do Notebook

In [ ]:
import torch

tns = torch.randn(10)
print(tns)

# verifica se gpu está disponível
if torch.cuda.is_available():
    device = torch.device('cuda')
else:
    device = torch.device('cpu')
print(device)
print()

# jogar informações na gpu
tensor = tns.to(device)
print(tns)

# Exercícios

## Usando view

- Crie um tensor aleatório tns1 com a dimensionalidade 7 x 7 x 3 e um outro tensor aleatório tns2 de 147 x 1. Modificando apenas tns1 some os dois tensores.

In [ ]:
import torch

tns1 = torch.randn(7, 7, 3)
tns2 = torch.randn(147, 1)

tns1_modific = tns1.view(-1, 1) # achata o tensor
print(tns1_modific + tns2)